#!/bin/sh
# PostToolUse hook (matcher: Bash) — WARN-only, never blocks.
#
# WHY THIS EXISTS
# Long sessions are often the largest cost multiplier a project has: the
# highest-context turns and subagent-heavy stretches tend to burn a
# disproportionate share of a session's budget. The cheapest fix is to CLEAR
# between waves of work. The reason teams don't is fear: clearing feels like
# losing the thread.
#
# A hook cannot run /clear (that is a user action, and correctly so). What it
# CAN do is make the clear free — by writing down, deterministically, everything
# a fresh session needs to pick the wave back up. Then the operator's decision
# is a keystroke, not a judgment call.
#
# WHAT IT WRITES
# .claude/wave-state.md — a GENERATED view: never hand-edited, regenerated from
# repo state on every run. It carries the session-local facts that a project's
# status doc deliberately does not: what merged just now, which PRs are open
# and where they sit in the review loop, which priority issues are overdue.
# The project's status doc (docs/STATE.md or equivalent) remains the source of
# truth for project status; this file is the wave's working set, disposable by
# design.
#
# It also checks whether the status doc's current-state block is stale
# relative to the merge that just landed, because clearing on top of a stale
# handoff is how a session loses the thread for real.
#
# Fires only on `gh pr merge`. Every other Bash call is a silent no-op.
# No mutation of tracked files, no network beyond the gh queries below, exit 0
# always (a broken hook must never block a merge).

set -eu

payload="$(cat)"

case "$payload" in
  *"gh pr merge"*) ;;
  *) exit 0 ;;
esac

cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0

OUT=".claude/wave-state.md"
STATE_DOC="docs/STATE.md"

# Everything below is best-effort: a failed query degrades to a blank section
# rather than a failed hook. `|| true` on each, and never `set -e` past here.
set +e

recent=$(git log --oneline -8 2>/dev/null)
openprs=$(gh pr list --state open --json number,title,reviewDecision,mergeable \
  --jq '.[] | "- #\(.number) \(.title) [review: \(.reviewDecision // "none")] [\(.mergeable)]"' 2>/dev/null)
p1s=$(gh issue list --state open --label "priority:P1" --limit 8 --json number,title \
  --jq '.[] | "- #\(.number) \(.title)"' 2>/dev/null)
head_sha=$(git rev-parse --short HEAD 2>/dev/null)

# Is the status doc's current-state block older than the code it describes?
# Compare last-commit dates: a current-state block older than the newest merge
# is stale by definition.
state_epoch=$(git log -1 --format=%ct -- "$STATE_DOC" 2>/dev/null)
head_epoch=$(git log -1 --format=%ct 2>/dev/null)
stale="unknown"
if [ -n "$state_epoch" ] && [ -n "$head_epoch" ]; then
  if [ "$state_epoch" -lt "$head_epoch" ]; then stale="STALE"; else stale="current"; fi
fi

{
  echo "# Wave state (GENERATED — do not hand-edit)"
  echo
  echo "Regenerated by .claude/hooks/wave-close-handoff.sh on every \`gh pr merge\`."
  echo "Disposable working set for the CURRENT wave. Project status lives in $STATE_DOC (source of truth)."
  echo
  echo "HEAD: \`$head_sha\` · $STATE_DOC current-state block: **$stale**"
  echo
  echo "## Open PRs (where the review loop stands)"
  echo
  if [ -n "$openprs" ]; then echo "$openprs"; else echo "_none — the wave is closed._"; fi
  echo
  echo "## Open P1"
  echo
  if [ -n "$p1s" ]; then echo "$p1s"; else echo "_none._"; fi
  echo
  echo "## Recent commits"
  echo
  echo '```'
  echo "$recent"
  echo '```'
} > "$OUT" 2>/dev/null

set -e

echo "REMINDER (post-merge doc-freshness gate): a PR merge just landed."
echo "-> Refresh $STATE_DOC's current-state block now (including in-flight work)."
echo "-> If a milestone cluster closed, update the milestone doc and republish any tracker artifact built from it."
echo "-> Run a doc-reconciliation pass before the next batch of work starts."
echo
echo "WAVE HANDOFF: .claude/wave-state.md regenerated (open PRs, open P1, recent commits)."

if [ "$stale" = "STALE" ]; then
  echo "$STATE_DOC's current-state block is OLDER than the merge that just landed. Refresh it BEFORE"
  echo "clearing — clearing on top of a stale handoff is how a session actually loses the thread."
else
  echo "$STATE_DOC's current-state block is current. If this wave is finished and no agents are"
  echo "running, a /clear costs nothing: $STATE_DOC + .claude/wave-state.md + the open issues carry it."
fi

exit 0
